apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: browsertrix
build:
  artifacts:
    # only put the backend in here since it's quite easy now
    # to run frontend locally and get hot reloading with yarn
    - image: docker.io/webrecorder/browsertrix-backend
      context: backend
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
        - src: 'btrixcloud/**/*'
          dest: .
portForward:
- resourceType: service
  resourceName: browsertrix-cloud-backend
  # assumes you are doing local dev in `default` namespace
  # if you aren't you need to change this manually
  namespace: default
  port: 8000
  localPort: 8000
deploy:
  helm:
    releases:
      - name: btrix
        chartPath: chart
        valuesFiles:
          - chart/values.yaml
        # See https://skaffold.dev/docs/deployers/helm/
        # must do this to make skaffold use local images with helm
        setValues:
          backend_image: docker.io/webrecorder/browsertrix-backend
          backend_pull_policy: "Never"
          # hot reloading doesn't work with default gunicorn command
          # so need to override to use uvicorn
          backend_api_command_override: 
            - uvicorn
            - btrixcloud.main:app_root
            - --reload
            - --host
            - "0.0.0.0"
            - --port
            - "8000"