apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: browsertrix
build:
  artifacts:
    # only put the backend in here since it's quite easy now
    # to run frontend locally and get hot reloading with yarn
    - image: docker.io/webrecorder/browsertrix-backend
      context: backend
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
        - src: 'btrixcloud/**/*'
          dest: .
portForward:
# so you can hit the API on `localhost:8000`
- resourceType: service
  resourceName: browsertrix-cloud-backend
  namespace: default
  port: 8000
  localPort: 8000
# for the debugger
- resourceType: deployment
  resourceName: browsertrix-cloud-backend
  namespace: default
  port: 5678
  localPort: 5678
deploy:
  helm:
    releases:
      - name: btrix
        chartPath: chart
        valuesFiles:
          - chart/values.yaml
          # local must come after values since it is expected to override
          - chart/local.yaml
        # See https://skaffold.dev/docs/deployers/helm/
        # must do this to make skaffold use local images with helm
        setValues:
          # hot reloading doesn't work with default gunicorn command
          # so need to override to use uvicorn
          # plus need to start the process with debugpy to debug
          backend_api_command_override:
            - sh
            - -c
            -  >
                pip install --no-input debugpy
                &&
                python -m debugpy --listen 0.0.0.0:5678
                -m uvicorn btrixcloud.main:app_root
                --reload --host 0.0.0.0 --port 8000
